version: '3.8'

services:
  frontend:
    build: ./frontend
    target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    stdin_open: true
    restart: always

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  mongo_data:
